let events = {
  sixthtriennialconferenceFeb2023 : {
    id : 'sixthtriennialconferenceFeb2023',
    title : '6th Triennial Conference',
    description : 'On the ocassion of 6th Triennial Conference, wherein activities of the organisation and articles concerning to retirees, senior citizens, banking industry and on other relevant topics are proposed to be discussed is scheduled from 24th February to 27th February, 2023. Delegates and Observers who wish to participate are requested to provide your details through the below registration link',
    startDate : "25th February, 2023",
    endDate : "27th February, 2023",
    action : 'Register',
    registeredUsers : ['1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31','32','33','34','35','36','37','38','39','40','41','42','43','44','45','46','47','48',]
  }
}

let users = {
  '1' : {
    id : '1',
    name : 'Kunta Hari Babu',
    mobile : 9848014081,
    staffCode : 4153,
    pfNo : 349674,
    gender : 'M',
    role : 'Delegate',
    spouseAccompanying : 'N',
    paymentDetails : {},
    emergencyDetails : {
      ecName : 'YLN Kumari',
      ecNumber : 9849050969,
      ecRelation : 'Wife', 
    },
    arrivalDetails : {
      arrivalDate : '25-02-23',
      arrivalTime : '09:00',
    },
    departureDetails : {
      departureDate : '28-02-23',
      departureTime : '08:00',
    },
    stayDetails : null,  
  },
  '2' : {
    id : '2',
    name : 'D.Nanharam',
    mobile : 9000434443,
    staffCode : 4165,
    pfNo : 318348,
    gender : 'M',
    role : 'Delegate',
    spouseAccompanying : 'N',
    paymentDetails : {},
    emergencyDetails : {
      ecName : 'D Kusa Ram',
      ecNumber : 9845499199,
      ecRelation : 'Son', 
    },
    arrivalDetails : {
      arrivalDate : '25-02-23',
      arrivalTime : '08:00',
    },
    departureDetails : {
      departureDate : '27-02-23',
      departureTime : '17:00',
    },
    stayDetails : null, 
  },
  '3' : {
    id : '3',
    name : 'Krishnamurthy V Varanasi',
    mobile : 9440012295,
    staffCode : 6826,
    pfNo : 386244,
    gender : 'M',
    role : 'Delegate',
    spouseAccompanying : 'N',
    paymentDetails : {},
    emergencyDetails : {
      ecName : 'Varanasi Phani',
      ecNumber : 9160500445,
      ecRelation : 'Son', 
    },
    arrivalDetails : {
      arrivalDate : '25-02-23',
      arrivalTime : '10:00',
    },
    departureDetails : {
      departureDate : '27-02-23',
      departureTime : '17:00',
    },
    stayDetails : null,  
  },
  '4' : {
    id : '4',
    name : 'Ravi Chander',
    mobile : 9885856210,
    staffCode : null,
    pfNo : null,
    gender : 'M',
    role : 'Delegate',
    spouseAccompanying : 'N',
    paymentDetails : {},
    emergencyDetails : null,
    arrivalDetails : {
      arrivalDate : '24-02-23',
      arrivalTime : '07:00',
    },
    departureDetails : {
      departureDate : '27-02-23',
      departureTime : '17:00',
    },
    stayDetails : null,  
  },
  '5' : {
    id : '5',
    name : 'Y.Tripuramba',
    mobile : 9246545149,
    staffCode : 2888,
    pfNo : 281856,
    gender : 'F',
    role : 'Delegate',
    spouseAccompanying : 'N',
    paymentDetails : {},
    emergencyDetails : {
      ecName : 'Mrs Aishwarya',
      ecNumber : 9880933044,
      ecRelation : 'Daughter', 
    },
    arrivalDetails : {
      arrivalDate : '25-02-23',
      arrivalTime : '05:00',
    },
    departureDetails : {
      departureDate : '27-02-23',
      departureTime : '17:00',
    },
    stayDetails : null, 
  },
  '6' : {
    id : '6',
    name : 'N.Ramgopal Rao',
    mobile : 9177673339,
    staffCode : 9790,
    pfNo : 457332,
    gender : 'M',
    role : 'Delegate',
    spouseAccompanying : 'N',
    paymentDetails : {},
    emergencyDetails : {
      ecName : 'N Shobha Devi',
      ecNumber : 9704143338,
      ecRelation : 'Wife', 
    },
    arrivalDetails : {
      arrivalDate : '25-02-23',
      arrivalTime : '05:00',
    },
    departureDetails : {
      departureDate : '27-02-23',
      departureTime : '17:00',
    },
    stayDetails : null,  
  },
  '7' : {
    id : '7',
    name : 'NSN Reddy',
    mobile : 9490213002,
    staffCode : 6507,
    pfNo : 371304,
    gender : 'M',
    role : 'Delegate',
    spouseAccompanying : 'N',
    paymentDetails : {},
    emergencyDetails : null,
    arrivalDetails : {
      arrivalDate : '24-02-23',
      arrivalTime : '07:00',
    },
    departureDetails : {
      departureDate : '27-02-23',
      departureTime : '17:00',
    },
    stayDetails : null,  
  },
  '8' : {
    id : '8',
    name : 'S.Krishna Kumar',
    mobile : 7032458383,
    staffCode : 3168,
    pfNo : 294078,
    gender : 'M',
    role : 'Delegate',
    spouseAccompanying : 'N',
    paymentDetails : {},
    emergencyDetails : {
      ecName : 'Dr S Dinesh',
      ecNumber : 9849970179,
      ecRelation : 'Son', 
    },
    arrivalDetails : {
      arrivalDate : '25-02-23',
      arrivalTime : '05:00',
    },
    departureDetails : {
      departureDate : '27-02-23',
      departureTime : '17:00',
    },
    stayDetails : null,  
  },
  '9' : {
    id : '9',
    name : 'A J Rama Rao',
    mobile : 9849141424,
    staffCode : 3105,
    pfNo : 293298,
    gender : 'M',
    role : 'Delegate',
    spouseAccompanying : 'N',
    paymentDetails : {},
    emergencyDetails : {
      ecName : 'Sushmitha',
      ecNumber : 9004220814,
      ecRelation : 'Daughter', 
    },
    arrivalDetails : {
      arrivalDate : '25-02-23',
      arrivalTime : '05:00',
    },
    departureDetails : {
      departureDate : '27-02-23',
      departureTime : '17:00',
    },
    stayDetails : null, 
  },
  '10' : {
    id : '10',
    name : 'K.Ramchander',
    mobile : 9849205255,
    staffCode : 7071,
    pfNo : 387714,
    gender : 'M',
    role : 'Delegate',
    spouseAccompanying : 'N',
    paymentDetails : {},
    emergencyDetails : null,
    arrivalDetails : {
      arrivalDate : '24-02-23',
      arrivalTime : '07:00',
    },
    departureDetails : {
      departureDate : '27-02-23',
      departureTime : '17:00',
    },
    stayDetails : null, 
  },
  '11' : {
    id : '11',
    name : 'N V Ramana',
    mobile : 9848444635,
    staffCode : 13092,
    pfNo : 555348,
    gender : 'M',
    role : 'Delegate',
    spouseAccompanying : 'N',
    paymentDetails : {},
    emergencyDetails : {
      ecName : 'Dr Phanisri',
      ecNumber : 7936876635,
      ecRelation : 'Daughter', 
    },
    arrivalDetails : {
      arrivalDate : '25-02-23',
      arrivalTime : '05:00',
    },
    departureDetails : {
      departureDate : '27-02-23',
      departureTime : '17:00',
    },
    stayDetails : null, 
  },
  '12' : {
    id : '12',
    name : 'K.Ramprasad',
    mobile : 9949986611,
    staffCode : 9823,
    pfNo : 459252,
    gender : 'M',
    role : 'Delegate',
    spouseAccompanying : 'N',
    paymentDetails : {},
    emergencyDetails : {
      ecName : 'K Swathi',
      ecNumber : 9951139439,
      ecRelation : 'Daughter', 
    },
    arrivalDetails : {
      arrivalDate : '25-02-23',
      arrivalTime : '05:00',
    },
    departureDetails : {
      departureDate : '27-02-23',
      departureTime : '17:00',
    },
    stayDetails : null, 
  },
  '13' : {
    id : '13',
    name : 'Kruttiventi Ravikumar',
    mobile : 9866270266,
    staffCode : 9137,
    pfNo : 432696,
    gender : 'M',
    role : 'Delegate',
    spouseAccompanying : 'N',
    paymentDetails : {},
    emergencyDetails : {
      ecName : 'K Tejaswi',
      ecNumber : 9966883325,
      ecRelation : 'Son', 
    },
    arrivalDetails : {
      arrivalDate : '25-02-23',
      arrivalTime : '05:00',
    },
    departureDetails : {
      departureDate : '27-02-23',
      departureTime : '17:00',
    },
    stayDetails : null, 
  },
  '14' : {
    id : '14',
    name : 'Soma Anantaramulu',
    mobile : 9492781190,
    staffCode : 10020,
    pfNo : 465378,
    gender : 'M',
    role : 'Delegate',
    spouseAccompanying : 'N',
    paymentDetails : {},
    emergencyDetails : {
      ecName : 'Soma Sumathi',
      ecNumber : 9247193185,
      ecRelation : 'Wife', 
    },
    arrivalDetails : {
      arrivalDate : '25-02-23',
      arrivalTime : '05:00',
    },
    departureDetails : {
      departureDate : '27-02-23',
      departureTime : '17:00',
    },
    stayDetails : null, 
  },
  '15' : {
    id : '15',
    name : 'Y L Prema Kumari',
    mobile : 9392646916,
    staffCode : null,
    pfNo : null,
    gender : 'F',
    role : 'Delegate',
    spouseAccompanying : 'Y',
    paymentDetails : {},
    emergencyDetails : {
      ecName : 'D Aashish',
      ecNumber : 9633773762,
      ecRelation : 'Son', 
    },
    arrivalDetails : {
      arrivalDate : '25-02-23',
      arrivalTime : '06:00',
    },
    departureDetails : {
      departureDate : '27-02-23',
      departureTime : '17:00',
    },
    stayDetails : null, 
  },
  '16' : {
    id : '16',
    name : 'B.Venkatapati Raju',
    mobile : null,
    staffCode : null,
    pfNo : null,
    gender : 'M',
    role : 'Delegate',
    spouseAccompanying : 'N',
    paymentDetails : {},
    emergencyDetails : null,
    arrivalDetails : {
      arrivalDate : '25-02-23',
      arrivalTime : '09:00',
    },
    departureDetails : {
      departureDate : '28-02-23',
      departureTime : '08:00',
    },
    stayDetails : null, 
  },
  '17' : {
    id : '17',
    name : 'BVV Kondal Rao',
    mobile : null,
    staffCode : null,
    pfNo : null,
    gender : 'M',
    role : 'Delegate',
    spouseAccompanying : 'N',
    paymentDetails : {},
    emergencyDetails : {
      ecName : 'Sandeep',
      ecNumber : 9676641414,
      ecRelation : 'Son', 
    },
    arrivalDetails : {
      arrivalDate : '25-02-23',
      arrivalTime : '09:00',
    },
    departureDetails : {
      departureDate : '28-02-23',
      departureTime : '08:00',
    },
    stayDetails : null, 
  },
  '18' : {
    id : '18',
    name : 'P K Rajeshwar Rao',
    mobile : 9666696844,
    staffCode : 17174,
    pfNo : 612622,
    gender : 'M',
    role : 'Delegate',
    spouseAccompanying : 'N',
    paymentDetails : {},
    emergencyDetails : {
      ecName : 'Abhinaya Kiran',
      ecNumber : 9177078798,
      ecRelation : 'Son-in-law', 
    },
    arrivalDetails : {
      arrivalDate : '25-02-23',
      arrivalTime : '07:00',
    },
    departureDetails : {
      departureDate : '27-02-23',
      departureTime : '08:00',
    },
    stayDetails : null, 
  },
  '19' : {
    id : '19',
    name : 'N.Ganesh',
    mobile : null,
    staffCode : 13220,
    pfNo : 558864,
    gender : 'M',
    role : 'Delegate',
    spouseAccompanying : 'N',
    paymentDetails : {},
    emergencyDetails : null,
    arrivalDetails : {
      arrivalDate : '25-02-23',
      arrivalTime : '05:00',
    },
    departureDetails : {
      departureDate : '28-02-23',
      departureTime : '08:00',
    },
    stayDetails : null, 
  },
  '20' : {
    id : '20',
    name : 'V Subramanyam',
    mobile : 9849650544,
    staffCode : 9137,
    pfNo : 432696,
    gender : 'M',
    role : 'Delegate',
    spouseAccompanying : 'N',
    paymentDetails : {},
    emergencyDetails : {
      ecName : 'V Sudha Rani',
      ecNumber : 9515836659,
      ecRelation : 'Wife', 
    },
    arrivalDetails : {
      arrivalDate : '25-02-23',
      arrivalTime : '09:00',
    },
    departureDetails : {
      departureDate : '28-02-23',
      departureTime : '08:00',
    },
    stayDetails : null, 
  },
  '21' : {
    id : '21',
    name : 'V.Sivanagi Reddy',
    mobile : null,
    staffCode : null,
    pfNo : null,
    gender : 'M',
    role : 'Delegate',
    spouseAccompanying : 'N',
    paymentDetails : {},
    emergencyDetails : null,
    arrivalDetails : {
      arrivalDate : '25-02-23',
      arrivalTime : '05:00',
    },
    departureDetails : {
      departureDate : '27-02-23',
      departureTime : '17:00',
    },
    stayDetails : null, 
  },
  '22' : {
    id : '22',
    name : 'S. Jai Kumar',
    mobile : null,
    staffCode : null,
    pfNo : null,
    gender : 'M',
    role : 'Delegate',
    spouseAccompanying : 'N',
    paymentDetails : {},
    emergencyDetails : null,
    arrivalDetails : {
      arrivalDate : '25-02-23',
      arrivalTime : 'NA',
    },
    departureDetails : null,
    stayDetails : null, 
  },
  '23' : {
    id : '23',
    name : 'M.Janakiram',
    mobile : 9444383625,
    staffCode : 2715,
    pfNo : 274686,
    gender : 'M',
    role : 'Delegate',
    spouseAccompanying : 'N',
    paymentDetails : {},
    emergencyDetails : {
      ecName : 'S Chitti',
      ecNumber : 8122915076,
      ecRelation : 'Son-in-law', 
    },
    arrivalDetails : {
      arrivalDate : '25-02-23',
      arrivalTime : '10:00',
    },
    departureDetails : {
      departureDate : '27-02-23',
      departureTime : '17:00',
    },
    stayDetails : null, 
  },
  '24' : {
    id : '24',
    name : 'Udaynath Patri',
    mobile : 9337901161,
    staffCode : 8387,
    pfNo : 426108,
    gender : 'M',
    role : 'Delegate',
    spouseAccompanying : 'N',
    paymentDetails : {},
    emergencyDetails : null,
    arrivalDetails : {
      arrivalDate : '25-02-23',
      arrivalTime : '06:00',
    },
    departureDetails : {
      departureDate : '27-02-23',
      departureTime : '16:00',
    },
    stayDetails : null, 
  },
  '25' : {
    id : '25',
    name : 'S.K.Dubey',
    mobile : 9347551661,
    staffCode : 3320,
    pfNo : 297714,
    gender : 'M',
    role : 'Delegate',
    spouseAccompanying : 'N',
    paymentDetails : {},
    emergencyDetails : {
      ecName : 'Aparna Santosh Dubey',
      ecNumber : 9373231661,
      ecRelation : 'Wife', 
    },
    arrivalDetails : {
      arrivalDate : '24-02-23',
      arrivalTime : '06:00',
    },
    departureDetails : {
      departureDate : '27-02-23',
      departureTime : '17:00',
    },
    stayDetails : null, 
  },
  '26' : {
    id : '26',
    name : 'Ramesh Kamath',
    mobile : 9860384427,
    staffCode : 3345,
    pfNo : 343134,
    gender : 'M',
    role : 'Delegate',
    spouseAccompanying : 'N',
    paymentDetails : {},
    emergencyDetails : {
      ecName : 'Sheela Kamath',
      ecNumber : 9960787099,
      ecRelation : 'Wife', 
    },
    arrivalDetails : {
      arrivalDate : '24-02-23',
      arrivalTime : '18:00',
    },
    departureDetails : {
      departureDate : '27-02-23',
      departureTime : '17:00',
    },
    stayDetails : null, 
  },
  '27' : {
    id : '27',
    name : 'Ms.Abha Basak',
    mobile : 9339867004,
    staffCode : 4938,
    pfNo : 333678,
    gender : 'F',
    role : 'Delegate',
    spouseAccompanying : 'N',
    paymentDetails : {},
    emergencyDetails : {
      ecName : 'Kartick Chandra Basak',
      ecNumber : 8961415545,
      ecRelation : 'Husband', 
    },
    arrivalDetails : {
      arrivalDate : '24-02-23',
      arrivalTime : '17:00',
    },
    departureDetails : {
      departureDate : '27-02-23',
      departureTime : '17:00',
    },
    stayDetails : null, 
  },
  '28' : {
    id : '28',
    name : 'P.Chandrashekar',
    mobile : 9440555191,
    staffCode : 11575,
    pfNo : 509604,
    gender : 'M',
    role : 'Delegate',
    spouseAccompanying : 'N',
    paymentDetails : {},
    emergencyDetails : null,
    arrivalDetails : {
      arrivalDate : '25-02-23',
      arrivalTime : '08:00',
    },
    departureDetails : {
      departureDate : '27-02-23',
      departureTime : '17:00',
    },
    stayDetails : null, 
  },
  '29' : {
    id : '29',
    name : 'GSV Krishna Rao',
    mobile : null,
    staffCode : null,
    pfNo : null,
    gender : 'M',
    role : 'Delegate',
    spouseAccompanying : 'N',
    paymentDetails : {},
    emergencyDetails : null,
    arrivalDetails : {
      arrivalDate : '25-02-23',
      arrivalTime : '07:00',
    },
    departureDetails : {
      departureDate : '27-02-23',
      departureTime : '17:00',
    },
    stayDetails : null, 
  },
  '30' : {
    id : '30',
    name : 'Yerikala Reddy',
    mobile : null,
    staffCode : null,
    pfNo : null,
    gender : 'M',
    role : 'Delegate',
    spouseAccompanying : 'N',
    paymentDetails : {},
    emergencyDetails : null,
    arrivalDetails : {
      arrivalDate : '25-02-23',
      arrivalTime : '07:00',
    },
    departureDetails : {
      departureDate : '27-02-23',
      departureTime : '17:00',
    },
    stayDetails : null, 
  },
  '31' : {
    id : '31',
    name : 'M. B. Shankara Rao',
    mobile : null,
    staffCode : 3349,
    pfNo : 298434,
    gender : 'M',
    role : 'Delegate',
    spouseAccompanying : 'N',
    paymentDetails : {},
    emergencyDetails : null,
    arrivalDetails : {
      arrivalDate : '25-02-23',
      arrivalTime : '09:00',
    },
    departureDetails : {
      departureDate : '28-02-23',
      departureTime : '08:00',
    },
    stayDetails : null, 
  },
  '32' : {
    id : '32',
    name : 'Y.Hanumantha Rao',
    mobile : null,
    staffCode : null,
    pfNo : null,
    gender : 'M',
    role : 'Delegate',
    spouseAccompanying : 'N',
    paymentDetails : {},
    emergencyDetails : {
      ecName : 'Y Kamala',
      ecNumber : 9491125540,
      ecRelation : 'Wife', 
    },
    arrivalDetails : {
      arrivalDate : '25-02-23',
      arrivalTime : '09:00',
    },
    departureDetails : {
      departureDate : '28-02-23',
      departureTime : '08:00',
    },
    stayDetails : null, 
  },
  '33' : {
    id : '33',
    name : 'N. Satyanarayana',
    mobile : 8019511951,
    staffCode : 4392,
    pfNo : 325698,
    gender : 'M',
    role : 'Delegate',
    spouseAccompanying : 'N',
    paymentDetails : {},
    emergencyDetails : {
      ecName : 'N Hanuteja',
      ecNumber : 9032857123,
      ecRelation : 'Son', 
    },
    arrivalDetails : {
      arrivalDate : '25-02-23',
      arrivalTime : '06:00',
    },
    departureDetails : {
      departureDate : '27-02-23',
      departureTime : '16:00',
    },
    stayDetails : null, 
  },
  '34' : {
    id : '34',
    name : 'N.Prabhakar',
    mobile : 9866139981,
    staffCode : null,
    pfNo : null,
    gender : 'M',
    role : 'Delegate',
    spouseAccompanying : 'N',
    paymentDetails : {},
    emergencyDetails : {
      ecName : 'Mrs Malleswari',
      ecNumber : 9440194580,
      ecRelation : 'Wife', 
    },
    arrivalDetails : {
      arrivalDate : '25-02-23',
      arrivalTime : '08:00',
    },
    departureDetails : {
      departureDate : '27-02-23',
      departureTime : '17:00',
    },
    stayDetails : null, 
  },
  '35' : {
    id : '35',
    name : 'R Mallikarjuna Rao',
    mobile : 9550070765,
    staffCode : 17594,
    pfNo : 617847,
    gender : 'M',
    role : 'Delegate',
    spouseAccompanying : 'N',
    paymentDetails : {},
    emergencyDetails : {
      ecName : 'R Kamakshi',
      ecNumber : 7032050036,
      ecRelation : 'Wife', 
    },
    arrivalDetails : {
      arrivalDate : '25-02-23',
      arrivalTime : '08:00',
    },
    departureDetails : {
      departureDate : '27-02-23',
      departureTime : '17:00',
    },
    stayDetails : null, 
  },
  '36' : {
    id : '36',
    name : 'G.V.Ramana Reddy',
    mobile : 9440428607,
    staffCode : 7881,
    pfNo : 408558,
    gender : 'M',
    role : 'Delegate',
    spouseAccompanying : 'N',
    paymentDetails : {},
    emergencyDetails : {
      ecName : 'Sri Sai',
      ecNumber : 8333855399,
      ecRelation : 'Daughter', 
    },
    arrivalDetails : {
      arrivalDate : '25-02-23',
      arrivalTime : '08:00',
    },
    departureDetails : {
      departureDate : '27-02-23',
      departureTime : '17:00',
    },
    stayDetails : null, 
  },
  '37' : {
    id : '37',
    name : 'C B Rao',
    mobile : 9951151611,
    staffCode : 10119,
    pfNo : 460254,
    gender : 'M',
    role : 'Delegate',
    spouseAccompanying : 'N',
    paymentDetails : {},
    emergencyDetails : {
      ecName : 'Sushmitha',
      ecNumber : 9902311144,
      ecRelation : 'Daughter', 
    },
    arrivalDetails : {
      arrivalDate : '25-02-23',
      arrivalTime : '06:00',
    },
    departureDetails : {
      departureDate : '28-02-23',
      departureTime : '08:00',
    },
    stayDetails : null, 
  },
  '38' : {
    id : '38',
    name : 'D.Koteshwara Rao',
    mobile : 9666687977,
    staffCode : 11559,
    pfNo : 509634,
    gender : 'M',
    role : 'Delegate',
    spouseAccompanying : 'N',
    paymentDetails : {},
    emergencyDetails : {
      ecName : 'Dr D Vinay',
      ecNumber : 8688455912,
      ecRelation : 'Son', 
    },
    arrivalDetails : {
      arrivalDate : '25-02-23',
      arrivalTime : '06:00',
    },
    departureDetails : {
      departureDate : '28-02-23',
      departureTime : '08:00',
    },
    stayDetails : null, 
  },
  '39' : {
    id : '39',
    name : 'B Pulla Rao(V.Surya Rao)',
    mobile : 9989619529,
    staffCode : null,
    pfNo : null,
    gender : 'M',
    role : 'Delegate',
    spouseAccompanying : 'N',
    paymentDetails : {},
    emergencyDetails : {
      ecName : 'B Tejaswi',
      ecNumber : 9963870303,
      ecRelation : 'Daughter', 
    },
    arrivalDetails : {
      arrivalDate : '25-02-23',
      arrivalTime : '06:00',
    },
    departureDetails : {
      departureDate : '27-02-23',
      departureTime : '17:00',
    },
    stayDetails : null, 
  },
  '40' : {
    id : '40',
    name : 'R Hanumantha Rao',
    mobile : 9848438408,
    staffCode : 10541,
    pfNo : 476712,
    gender : 'M',
    role : 'Delegate',
    spouseAccompanying : 'N',
    paymentDetails : {},
    emergencyDetails : null,
    arrivalDetails : {
      arrivalDate : '24-02-23',
      arrivalTime : '06:00',
    },
    departureDetails : {
      departureDate : '27-02-23',
      departureTime : '17:00',
    },
    stayDetails : null, 
  },
  '41' : {
    id : '41',
    name : 'N.Krishna',
    mobile : 9849263524,
    staffCode : 12384,
    pfNo : 529872,
    gender : 'M',
    role : 'Delegate',
    spouseAccompanying : 'N',
    paymentDetails : {},
    emergencyDetails : {
      ecName : 'Smt Thejaswi',
      ecNumber : 9989095596,
      ecRelation : 'Daughter', 
    },
    arrivalDetails : {
      arrivalDate : '25-02-23',
      arrivalTime : '06:00',
    },
    departureDetails : {
      departureDate : '27-02-23',
      departureTime : '17:00',
    },
    stayDetails : null, 
  },
  '42' : {
    id : '42',
    name : 'V Jagan Mohan Rao',
    mobile : 9885267569,
    staffCode : 10962,
    pfNo : 480432,
    gender : 'M',
    role : 'Delegate',
    spouseAccompanying : 'N',
    paymentDetails : {},
    emergencyDetails : {
      ecName : 'V Rajya Lakshmi',
      ecNumber : 7675924848,
      ecRelation : 'Wife', 
    },
    arrivalDetails : {
      arrivalDate : '25-02-23',
      arrivalTime : '09:00',
    },
    departureDetails : {
      departureDate : '28-02-23',
      departureTime : '08:00',
    },
    stayDetails : null, 
  },
  '43' : {
    id : '43',
    name : 'G V Gopal (MSRK Prasad)',
    mobile : 8106479204,
    staffCode : null,
    pfNo : null,
    gender : 'M',
    role : 'Delegate',
    spouseAccompanying : 'N',
    paymentDetails : {},
    emergencyDetails : {
      ecName : 'Raja Rajeswari',
      ecNumber : 8897179204,
      ecRelation : 'Wife', 
    },
    arrivalDetails : {
      arrivalDate : '24-02-23',
      arrivalTime : '09:00',
    },
    departureDetails : {
      departureDate : '27-02-23',
      departureTime : '05:00',
    },
    stayDetails : null, 
  },
  '44' : {
    id : '44',
    name : 'N.Krishna Mohan',
    mobile : 9986191986,
    staffCode : 8636,
    pfNo : 429606,
    gender : 'M',
    role : 'Delegate',
    spouseAccompanying : 'N',
    paymentDetails : {},
    emergencyDetails : {
      ecName : 'N Ravi Teja',
      ecNumber : 9989681600,
      ecRelation : 'Son', 
    },
    arrivalDetails : {
      arrivalDate : '25-02-23',
      arrivalTime : '09:00',
    },
    departureDetails : {
      departureDate : '28-02-23',
      departureTime : '08:00',
    },
    stayDetails : null, 
  },
  '45' : {
    id : '45',
    name : 'G.Vasudeva Murthy',
    mobile : 8008104042,
    staffCode : 8077,
    pfNo : 415272,
    gender : 'M',
    role : 'Delegate',
    spouseAccompanying : 'N',
    paymentDetails : {},
    emergencyDetails : {
      ecName : 'Vinaykumar V',
      ecNumber : 9008490074,
      ecRelation : 'Son-in-law', 
    },
    arrivalDetails : {
      arrivalDate : '24-02-23',
      arrivalTime : '07:00',
    },
    departureDetails : {
      departureDate : '27-02-23',
      departureTime : '17:00',
    },
    stayDetails : null, 
  },
  '46' : {
    id : '46',
    name : 'M.Ganesh Kumar',
    mobile : 9440663468,
    staffCode : 14293,
    pfNo : 601325,
    gender : 'M',
    role : 'Delegate',
    spouseAccompanying : 'N',
    paymentDetails : {},
    emergencyDetails : {
      ecName : 'Dr N Padmaja',
      ecNumber : 9949638922,
      ecRelation : 'Wife', 
    },
    arrivalDetails : {
      arrivalDate : '25-02-23',
      arrivalTime : '09:00',
    },
    departureDetails : {
      departureDate : '28-02-23',
      departureTime : '08:00',
    },
    stayDetails : null, 
  },
  '47' : {
    id : '47',
    name : 'Jatindra Samal',
    mobile : null,
    staffCode : null,
    pfNo : null,
    gender : 'M',
    role : 'Observer',
    spouseAccompanying : 'N',
    paymentDetails : {},
    emergencyDetails : null,
    arrivalDetails : {
      arrivalDate : '25-02-23',
      arrivalTime : '11:00',
    },
    departureDetails : {
      departureDate : '27-02-23',
      departureTime : '16:00',
    },
    stayDetails : null, 
  },
  '48' : {
    id : '48',
    name : 'Sudhir Kumar',
    mobile : null,
    staffCode : null,
    pfNo : null,
    gender : 'M',
    role : 'Observer',
    spouseAccompanying : 'N',
    paymentDetails : {},
    emergencyDetails : null,
    arrivalDetails : null,
    departureDetails : null,
    stayDetails : null, 
  },
}

// function generateUID () {
//   return Math.random().toString(36).substring(2, 15) + Math.random().toString(36).substring(2, 15)
// }

export function _getUsers () {
  return new Promise((res, rej) => {
    setTimeout(() => res({...users}), 1000)
  })
}

export function _getEvents () {
  return new Promise((res, rej) => {
    setTimeout(() => res({...events}), 1000)
  })
}
